language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: srIaPQWVO9JZPXqEZmxGTlVrWJE/qnDa2IK8sqK6KBUs0baCebQEwyHIa/eX1V+LqJFji/0ut/IbmEPwRc97DLsEIYEAXxzMKeyv5U3g5iEP++LwAKowiHEruU33M0vSOFP3tnVj/c7ysSYXg2thr70bJoqTo5QgwjKN4R2H0uQt7eRgnIoOOr9JaRE6qpWrIP1cJYAhAdTV8RdcxRf2cfY8lf9xh+iXjE9ek540wcA4tt0AS3rggOt9LlGbwlNKM4ZXSTZccGYP4bH2adbi8PK0lC3IhZQjjV8IKCgsK/HAk1zKstdKt/jo2MgUzbess5NzU+dRursrvOeQFFzAlvJpHDYkGkv7kqgglw4WggK6fBt/G44aycsdn1N8iCwPubhoO5ebXM+fXkVyjBSCTt24ngJj2Umid8B3dl25WID2LJjK+PDNIb36bQQmkQaJ4coo5VXn+lWXfFIMwpUvVp3wL0mD1I5G/cb1Mg6qw5VG53lUKIyzocon4sPqgvA6x8R2OOtUZUn4iZfvtdiNETnaYFU8uONd7THPbbx6w2firKm7lxgaG3cp9h+Fi8Ttp9V+DFOCjear2ff2s7Br1zot9hGS14qd2Y7dXStUMT+54PYmaMbCQJk3Irx9O4LSFhDGVI7bEVdyiwB/R9+/I6xKMRdLqpzS28tL+1ZGmys=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-windows-file-plugin
notifications:
  hipchat:
    rooms:
      secure: C2+JN4OKsPxOk0InkCg6/IElfJ1MSAZ8QeU3SIP8BlxOiLSOxKsWsn2mIbFNM3EiPMyo1LWF0C2rabFHLNuQIaF7QLJB2HZmBvwQjcPCgPNLoEhsk+FXO6Zg1palwqXKDoFoLwoehiaZc7z6JPhQsG9ZPDBQfWDI2xhUv1jicZN90MmlJblTowX7hTtoB0933o1myUZDWs9KlAn+BbZAYybNKdPO6g8gYIdICexaz2YsTKN8cosPR5j06xh9IF05y2S+uWkoN7cQZt6kIX11haDN4Fy/3z/yex8kB00zBH85jZPwmAAezjN7nKQeIjXh/peYmdcE32q1FVxJiaAmR6nIyzzGNxMnYR8UJUUmelmDhY27ZMWxUzrtG3Mj8f5VopemWCa0fl/S2HC00T1vNNbsTxTo75kmWfae/3+lbtvd6bOs9VWkdQnXU5tioRk88PXIaymF94wPMr0R5huyMOz/RAy7kZ1kMisJms21UvD0lzN9j1STiPUXRuY4Z9s63XlVypRnb+KYWi6CB8X+LpalRrECgmfDMqLpJQgnk2cv6RV2c3y0J0XZnqny4+LBoCTdcanwTR3aJt4QTSptwAWqY//WQwpYrlsQRohIi93AcSPpIc6JgAWUydUDprVw3SBmU3zaY+TYrEDTITCIdzDumATPINTJHKBv8sv1quY=
