language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: stmqGc6uabN87it1YE6SLGehyUomO4ehBec3NWWQyjLlMgp+sWjLwIEehSviIb88KAnUDpJ9aHW012sZK5GEoq7xtQRseWD4A6G+fb9fCAS9o1BCZIlEcTYQG0aBtbSlyPuPbDW9bRGQ/L5Wj1JHcFB78P1b3qnMap0c0Z5pLRokb73zzSOCORvmEic8VeoYtXjIn/NXzdxkSAe07OhH2RhbxOq0IUd6BdRpUGpCj2iD2G7zHNL7gg+NdKpLC20bYrAz913VGBhK//0ujrfkRGSVnb1Pz64nZP91bLYHPD0luiGi/4o2HFY3UYmSARNJz+3/uy8lXwa9NR5wLq5BhqTRzn/TRH1PQlJbybjk7/YO8d2xHvOWF8ZR/FB2hUM3Nkwzxo9al479QCiM/lmKyTjXkj68oqJiCchyZcc/fmPVLwQ9nTzB5OQBcZZbaHTW+6hqTefq3e0IIFtxFc6JdAbLvCFqxr647/8ltJqtVCKhoHAnP7xpPyx5lNmlrBiJVMzbxZMvEwI95lntUxUS14eDhwhVIWV7WmvHUGkreUytVwyRTzuacuLQaZz8ZtMdEfm8rBN5JyDIOf3c+9TyoMfc6vr0auGq8X26Ch24NtV0/gFZarEVwCWz2tR1gP52zJN1EssF45dCB/I20R1bge/Hmj9w84AepVEM5fqjBGU=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-windows-file-plugin
notifications:
  hipchat:
    rooms:
      secure: C2+JN4OKsPxOk0InkCg6/IElfJ1MSAZ8QeU3SIP8BlxOiLSOxKsWsn2mIbFNM3EiPMyo1LWF0C2rabFHLNuQIaF7QLJB2HZmBvwQjcPCgPNLoEhsk+FXO6Zg1palwqXKDoFoLwoehiaZc7z6JPhQsG9ZPDBQfWDI2xhUv1jicZN90MmlJblTowX7hTtoB0933o1myUZDWs9KlAn+BbZAYybNKdPO6g8gYIdICexaz2YsTKN8cosPR5j06xh9IF05y2S+uWkoN7cQZt6kIX11haDN4Fy/3z/yex8kB00zBH85jZPwmAAezjN7nKQeIjXh/peYmdcE32q1FVxJiaAmR6nIyzzGNxMnYR8UJUUmelmDhY27ZMWxUzrtG3Mj8f5VopemWCa0fl/S2HC00T1vNNbsTxTo75kmWfae/3+lbtvd6bOs9VWkdQnXU5tioRk88PXIaymF94wPMr0R5huyMOz/RAy7kZ1kMisJms21UvD0lzN9j1STiPUXRuY4Z9s63XlVypRnb+KYWi6CB8X+LpalRrECgmfDMqLpJQgnk2cv6RV2c3y0J0XZnqny4+LBoCTdcanwTR3aJt4QTSptwAWqY//WQwpYrlsQRohIi93AcSPpIc6JgAWUydUDprVw3SBmU3zaY+TYrEDTITCIdzDumATPINTJHKBv8sv1quY=
