language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: xXLstwDqMzbRnCKa6ojg6DWfyBp4tnQqr+TvsIm9cRDxLUtHeaSVMJ1LtNqtFfkaFk9IlvYfjuCslR5uMRR57iFwfl2O940yPDuJJ/TAIsuwAjG2zXBetjvfWHO539SCdVKBA+8f0zagxMCWbp5+PzsJ0zJEAVo5FAuraH30iBKmZ6MKiCayeyYkrOEsYT+L5FtGA9ZaC7w9DLjRKgdj9qRsXyRbDHjrAcOl1Co1zTKS9PzDgJdzG2RGDc0TGtqGkP9BacP94jUInGKoriW0VR/N6HCiFkfWR9IYMjHQPDPaHH+XffNvwjv8Xl38ltabNo+0KP2JPzs8bQk4Pc+da/GvuW385Vv9GxWMx37CEA1pGAlyquB/qQH5iOIZXBIzWXO+jJKFWKYY85RzugHuCQ9BPkCv227vm57PIoWRIeafh0PWtUVmZqo71waWptR7skE05Azhds/Khm7yST3IylMLgNFMmQ07UPI3jGBSz5CRpqysv+SxXdO/Dso3YdTt9ILWHLC5gWm5nEePxfxVjdPAHAmg9nwLvcjgA95QQcz2eyzibm7PGyhgkujxgYenOIh+3ScgMGcrSTF4ttXCc18XbXPEZf6BqxIAoR5sqZr0ERvlj2zFwE0y+d+O8XJGcBYSxgVHdjXb7Oj2wn+QtRj2noBGYR/kFIEcmLdvpNg=
  file: build/distibutions/windows-file-plugin-1.0.4.xldp
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-windows-file-plugin
notifications:
  hipchat:
    rooms:
      secure: C2+JN4OKsPxOk0InkCg6/IElfJ1MSAZ8QeU3SIP8BlxOiLSOxKsWsn2mIbFNM3EiPMyo1LWF0C2rabFHLNuQIaF7QLJB2HZmBvwQjcPCgPNLoEhsk+FXO6Zg1palwqXKDoFoLwoehiaZc7z6JPhQsG9ZPDBQfWDI2xhUv1jicZN90MmlJblTowX7hTtoB0933o1myUZDWs9KlAn+BbZAYybNKdPO6g8gYIdICexaz2YsTKN8cosPR5j06xh9IF05y2S+uWkoN7cQZt6kIX11haDN4Fy/3z/yex8kB00zBH85jZPwmAAezjN7nKQeIjXh/peYmdcE32q1FVxJiaAmR6nIyzzGNxMnYR8UJUUmelmDhY27ZMWxUzrtG3Mj8f5VopemWCa0fl/S2HC00T1vNNbsTxTo75kmWfae/3+lbtvd6bOs9VWkdQnXU5tioRk88PXIaymF94wPMr0R5huyMOz/RAy7kZ1kMisJms21UvD0lzN9j1STiPUXRuY4Z9s63XlVypRnb+KYWi6CB8X+LpalRrECgmfDMqLpJQgnk2cv6RV2c3y0J0XZnqny4+LBoCTdcanwTR3aJt4QTSptwAWqY//WQwpYrlsQRohIi93AcSPpIc6JgAWUydUDprVw3SBmU3zaY+TYrEDTITCIdzDumATPINTJHKBv8sv1quY=
